export const PLANNING_WINDOW_PRESETS = [
    {
        id: 'focused-work',
        title: 'Focused work',
        subtitle: 'Protect time for work and concentration',
        description: 'Use this for concentrated work, job-related tasks, administrative work, writing, planning, or deep-focus sessions.',
        exampleTasks: ['project work', 'emails', 'planning', 'admin'],
        primaryCategory: 'Work',
        secondaryCategories: ['Education'],
        behaviorMode: 'PREFERRED',
        targetPlacementMode: 'ALLOW_ELSEWHERE',
        suggestedNames: ['Morning Work Block', 'Focused Work Time', 'Work Focus'],
    },
    {
        id: 'studying-learning',
        title: 'Studying / learning',
        subtitle: 'Reserve time for learning and exam preparation',
        description: 'Use this for studying, lectures, reading, exam preparation, tutorials, or learning sessions.',
        exampleTasks: ['study session', 'reading', 'coursework', 'revision'],
        primaryCategory: 'Education',
        secondaryCategories: ['Work'],
        behaviorMode: 'PREFERRED',
        targetPlacementMode: 'ALLOW_ELSEWHERE',
        suggestedNames: ['Study Block', 'Learning Time', 'Exam Prep'],
    },
    {
        id: 'household-duties',
        title: 'Household / duties',
        subtitle: 'Group chores and obligations',
        description: 'Use this for household chores, cleaning, laundry, paperwork, bills, shopping, and other obligations.',
        exampleTasks: ['laundry', 'cleaning', 'bills', 'paperwork'],
        primaryCategory: 'Duty',
        secondaryCategories: ['Health'],
        behaviorMode: 'PREFERRED',
        targetPlacementMode: 'ALLOW_ELSEWHERE',
        suggestedNames: ['Duty Block', 'Household Time', 'Chore Window'],
    },
    {
        id: 'health',
        title: 'Health',
        subtitle: 'Protect time for health routines',
        description: 'Use this for medication, therapy exercises, doctor-related preparation, recovery routines, or health maintenance.',
        exampleTasks: ['medication', 'therapy exercises', 'recovery', 'health admin'],
        primaryCategory: 'Health',
        secondaryCategories: ['Sport', 'Duty'],
        behaviorMode: 'PREFERRED',
        targetPlacementMode: 'PREFER_INSIDE_WINDOW',
        suggestedNames: ['Health Routine', 'Recovery Block', 'Therapy Time'],
    },
    {
        id: 'sport-fitness',
        title: 'Sport / fitness',
        subtitle: 'Plan movement and exercise',
        description: 'Use this for workouts, walks, stretching, training, sports, or movement breaks.',
        exampleTasks: ['workout', 'walk', 'stretching', 'gym'],
        primaryCategory: 'Sport',
        secondaryCategories: ['Health', 'Leisure'],
        behaviorMode: 'PREFERRED',
        targetPlacementMode: 'ALLOW_ELSEWHERE',
        suggestedNames: ['Workout Block', 'Fitness Time', 'Movement Window'],
    },
    {
        id: 'social-life',
        title: 'Social life',
        subtitle: 'Make room for people and relationships',
        description: 'Use this for calls, messages, meeting friends, family time, relationship care, or social planning.',
        exampleTasks: ['call friend', 'family time', 'messages', 'social planning'],
        primaryCategory: 'Social',
        secondaryCategories: ['Leisure'],
        behaviorMode: 'PREFERRED',
        targetPlacementMode: 'ALLOW_ELSEWHERE',
        suggestedNames: ['Social Time', 'Evening Social Block', 'Family and Friends'],
    },
    {
        id: 'errands',
        title: 'Errands',
        subtitle: 'Group outside tasks and short trips',
        description: 'Use this for outside-the-house practical tasks like shopping, pharmacy, post office, pickups, or admin trips.',
        exampleTasks: ['shopping', 'pharmacy', 'post office', 'pickup'],
        displayCategory: 'Errands',
        primaryCategory: 'Duty',
        secondaryCategories: ['Health', 'Social'],
        behaviorMode: 'PREFERRED',
        targetPlacementMode: 'PREFER_INSIDE_WINDOW',
        suggestedNames: ['Errand Block', 'Outside Tasks', 'Shopping and Admin'],
    },
    {
        id: 'recovery-free-time',
        title: 'Recovery / free time',
        subtitle: 'Protect rest and decompression',
        description: 'Use this for rest, breaks, recovery, hobbies, decompression, or protected free time.',
        exampleTasks: ['break', 'rest', 'hobby', 'recovery'],
        primaryCategory: 'Leisure',
        secondaryCategories: ['Health'],
        behaviorMode: 'STRICT',
        targetPlacementMode: 'KEEP_INSIDE_WINDOW',
        suggestedNames: ['Recovery Block', 'Free Time', 'Rest Window'],
    },
    {
        id: 'balance-mixed',
        title: 'Balance / mixed tasks',
        subtitle: 'Let the scheduler choose what fits best',
        description: 'Use this when the time block does not have one strong focus and the scheduler may choose whatever fits best.',
        exampleTasks: ['mixed backlog', 'small tasks', 'flexible planning'],
        primaryCategory: 'Work',
        secondaryCategories: ['Duty', 'Health', 'Sport', 'Social', 'Leisure', 'Education'],
        behaviorMode: 'PREFERRED',
        targetPlacementMode: 'ALLOW_ELSEWHERE',
        suggestedNames: ['Flexible Block', 'Mixed Task Time', 'General Planning Window'],
    },
    {
        id: 'custom',
        title: 'Custom',
        subtitle: 'Build your own scheduling rule',
        description: 'Create your own Planning Window by choosing the main task category, optional additional categories, days, times, and strictness.',
        exampleTasks: [],
        primaryCategory: 'Work',
        secondaryCategories: [],
        behaviorMode: 'PREFERRED',
        targetPlacementMode: 'ALLOW_ELSEWHERE',
        suggestedNames: ['Custom Planning Window'],
    },
];

export const TIME_PRESETS = [
    { label: 'Weekday mornings', dayMask: 31, startTime: '08:00', endTime: '12:00' },
    { label: 'Weekday afternoons', dayMask: 31, startTime: '13:00', endTime: '17:00' },
    { label: 'Weekday evenings', dayMask: 31, startTime: '18:00', endTime: '21:00' },
    { label: 'Weekend mornings', dayMask: 96, startTime: '09:00', endTime: '12:00' },
    { label: 'Weekend afternoons', dayMask: 96, startTime: '13:00', endTime: '17:00' },
];
