server:
  port: 8085

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-scheduling:5432/scheduling_service_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS:3600000}

grpc:
  client:
    task-service:
      address: static://task-service:9090
      negotiation-type: plaintext

    customer-service:
      address: static://customer-service:9090
      negotiation-type: plaintext

    zone-service:
      address: static://customer-service:9090
      negotiation-type: plaintext

    routing-service:
      address: static://routing-service:9090
      negotiation-type: plaintext

  server:
    port: 9090
    security:
      enabled: false
